// The sound palette: marimba + soft woodblock (CLAUDE.md §4). All samples are
// pre-generated by scripts/generate-sounds.mjs and pre-loaded here — nothing is
// synthesized at runtime. Tick pitches live on a C pentatonic scale; when
// background music arrives (M5) they quantize to its key.

import { createAudioPlayer, setAudioModeAsync, type AudioPlayer } from 'expo-audio';

import chordSrc from '@/assets/sounds/chord.wav';
import musicDay from '@/assets/sounds/music-day.wav';
import musicDusk from '@/assets/sounds/music-dusk.wav';
import musicMorning from '@/assets/sounds/music-morning.wav';
import musicNight from '@/assets/sounds/music-night.wav';
import marimba00 from '@/assets/sounds/marimba-00.wav';
import marimba01 from '@/assets/sounds/marimba-01.wav';
import marimba02 from '@/assets/sounds/marimba-02.wav';
import marimba03 from '@/assets/sounds/marimba-03.wav';
import marimba04 from '@/assets/sounds/marimba-04.wav';
import marimba05 from '@/assets/sounds/marimba-05.wav';
import marimba06 from '@/assets/sounds/marimba-06.wav';
import marimba07 from '@/assets/sounds/marimba-07.wav';
import marimba08 from '@/assets/sounds/marimba-08.wav';
import marimba09 from '@/assets/sounds/marimba-09.wav';
import knockSrc from '@/assets/sounds/knock.wav';
import woodblockSrc from '@/assets/sounds/woodblock.wav';
import { useSettings } from '@/lib/store/settings';
import { daypartOf, type Daypart } from '@/lib/theme';

const marimbaSources = [
  marimba00,
  marimba01,
  marimba02,
  marimba03,
  marimba04,
  marimba05,
  marimba06,
  marimba07,
  marimba08,
  marimba09,
];

const musicSources: Record<Daypart, number> = {
  morning: musicMorning,
  day: musicDay,
  dusk: musicDusk,
  night: musicNight,
};

let marimbaPlayers: AudioPlayer[] = [];
let woodblockPlayer: AudioPlayer | null = null;
let knockPlayer: AudioPlayer | null = null;
let chordPlayer: AudioPlayer | null = null;
let musicPlayers: Partial<Record<Daypart, AudioPlayer>> = {};
let playingDaypart: Daypart | null = null;
let ready = false;

const timers: ReturnType<typeof setTimeout>[] = [];

export async function initAudio(): Promise<void> {
  if (ready) return;
  try {
    await setAudioModeAsync({
      playsInSilentMode: true,
      interruptionModeAndroid: 'duckOthers',
      interruptionMode: 'mixWithOthers',
    });
    marimbaPlayers = marimbaSources.map((src) => createAudioPlayer(src));
    woodblockPlayer = createAudioPlayer(woodblockSrc);
    knockPlayer = createAudioPlayer(knockSrc);
    chordPlayer = createAudioPlayer(chordSrc);
    musicPlayers = Object.fromEntries(
      (Object.keys(musicSources) as Daypart[]).map((dp) => {
        const player = createAudioPlayer(musicSources[dp]);
        player.loop = true;
        player.volume = MUSIC_VOLUME;
        return [dp, player];
      })
    );
    ready = true;
    updateMusic();
  } catch (e) {
    // Sound is identity, but never a blocker — the app stays silent on failure.
    console.warn('Audio init failed', e);
  }
}

function soundEnabled(): boolean {
  return ready && useSettings.getState().soundOn;
}

function trigger(player: AudioPlayer | null, volume = 1): void {
  if (!player || !soundEnabled()) return;
  try {
    player.seekTo(0);
    player.volume = volume;
    player.play();
  } catch {
    // A dropped tick is better than a dropped frame.
  }
}

function later(fn: () => void, ms: number): void {
  timers.push(setTimeout(fn, ms));
}

function clampIndex(i: number): number {
  return Math.max(0, Math.min(marimbaPlayers.length - 1, Math.round(i)));
}

/**
 * One drag tick. `intensity` 0..1 maps drag speed onto the pentatonic scale —
 * slow drags plink low and quiet, fast flings climb high and bright.
 */
export function playTick(intensity: number): void {
  const idx = clampIndex(intensity * (marimbaPlayers.length - 1));
  trigger(marimbaPlayers[idx], 0.35 + 0.45 * intensity);
}

/** Pickup = soft woodblock tap. */
export function playPickup(): void {
  trigger(woodblockPlayer, 0.6);
}

/** Locked-in throw = quick two-note rising marimba, brighter with harder flings. */
export function playThrowLock(intensity = 0.5): void {
  const base = clampIndex(2 + intensity * 4);
  trigger(marimbaPlayers[base], 0.8);
  later(() => trigger(marimbaPlayers[clampIndex(base + 2)], 0.9), 90);
}

/** Next pair dealing in: two quick low plinks. */
export function playDealIn(): void {
  trigger(marimbaPlayers[0], 0.4);
  later(() => trigger(marimbaPlayers[2], 0.4), 70);
}

/** Gift shake = 3–4 quick woodblock knocks (the gift knocking from inside). */
export function playGiftKnock(): void {
  trigger(knockPlayer, 0.9);
  later(() => trigger(knockPlayer, 0.9), 100);
  later(() => trigger(knockPlayer, 0.8), 200);
  later(() => trigger(knockPlayer, 1.0), 330);
}

/** Reveal = ascending three-note melody resolving into a soft chord. */
export function playRevealMelody(): void {
  trigger(marimbaPlayers[3], 0.8);
  later(() => trigger(marimbaPlayers[5], 0.8), 190);
  later(() => trigger(marimbaPlayers[7], 0.85), 380);
  later(() => trigger(chordPlayer, 0.9), 640);
}

// ---------------------------------------------------------------------------
// Background music: gentle loops that change with the time of day, quiet by
// design, always behind the global mute AND its own toggle. Every loop stays
// in the C-pentatonic family, so drag ticks are always in key (§4).

const MUSIC_VOLUME = 0.22;

/** Start/stop/switch the loop to match the clock and the toggles. Safe to
 * call any time — on app start, foreground, or settings changes. */
export function updateMusic(): void {
  if (!ready) return;
  const { soundOn, musicOn } = useSettings.getState();
  const wanted = soundOn && musicOn ? daypartOf() : null;
  if (wanted === playingDaypart) return;

  try {
    if (playingDaypart) musicPlayers[playingDaypart]?.pause();
    if (wanted) {
      const player = musicPlayers[wanted];
      if (player) {
        player.volume = MUSIC_VOLUME;
        player.play();
      }
    }
    playingDaypart = wanted;
  } catch {
    playingDaypart = null;
  }
}
